/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmSubsifiosPendentesNoPortal.java
 *
 * Created on 21/02/2014, 10:35:21
 */
package Formularios;

//import bsh.ParseException;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.joda.time.DateTime;
import subsidio_pendentes_no_portal.BuscasSubsidiosPendentes;
import subsidio_pendentes_no_portal.BuscasTerceirizacao;
import subsidio_pendentes_no_portal.BuscasTerceirizacao_2teste_while;

/**
 *
 * @author f7057419
 */
public final class frmSubsifiosPendentesNoPortal extends javax.swing.JFrame {

    /** Creates new form frmSubsifiosPendentesNoPortal */
    public frmSubsifiosPendentesNoPortal() {
        initComponents();
       txtChave.setText(System.getProperty("user.name").toUpperCase());
       txtSenha.requestFocus();
        Color corlDoformulario = new Color(243,195,215);        
        
        getContentPane().setBackground(corlDoformulario); //Aqui o método chave
       
        setDefaultCloseOperation(EXIT_ON_CLOSE);
       //Altera o tamanho do form
      // setBounds(300, 200, 400, 300);
       setBounds(600, 300, 680, 480);
        fechaApos2Horas();
    }
    
    
     public void fechaApos2Horas(){
           new Thread() {
               @Override 
               public void run() { 
                    
                    DateTime dateTime1 = new DateTime();
                    System.out.println(dateTime1.getMinuteOfDay());
                   
                   
                 //  DateTime dateTime2 = dateTime1.plusHours(1); 
                   DateTime dateTime2 = dateTime1.plusMinutes(120); 
                   
                   System.out.println(dateTime2.getMinuteOfDay());
                   
                   while ( (dateTime1.getMinuteOfDay()) != (dateTime2.getMinuteOfDay())) {                       
                       dateTime1 = new DateTime();               
                              
                   }
                   
                   
                   System.exit(0); 
                   

               }    
       }.start();
                   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtChave = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(145, 170, 252));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subsidio_pendentes_no_portal/NOME_SUBSIDIOS.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 650, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subsidio_pendentes_no_portal/NOME_m.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 420, 274, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subsidio_pendentes_no_portal/bb_logo1.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 80, 55, 55);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subsidio_pendentes_no_portal/SAIRM.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 340, 61, 61);

        txtChave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtChave.setText("F");
        txtChave.setToolTipText("");
        txtChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChaveActionPerformed(evt);
            }
        });
        txtChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChaveKeyReleased(evt);
            }
        });
        getContentPane().add(txtChave);
        txtChave.setBounds(120, 90, 107, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(14, 106, 51));
        jLabel7.setText("Senha:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 90, 82, 29);

        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSenha.setText("65414038");
        txtSenha.setToolTipText("");
        getContentPane().add(txtSenha);
        txtSenha.setBounds(370, 90, 128, 30);

        jButton1.setBackground(new java.awt.Color(243, 186, 215));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(14, 106, 51));
        jButton1.setText("Terceirização");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 200, 180, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(14, 106, 51));
        jLabel8.setText("Chave:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 90, 82, 29);

        jButton2.setBackground(new java.awt.Color(243, 195, 215));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(14, 106, 51));
        jButton2.setText("Subsidios Pendentes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 140, 180, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subsidio_pendentes_no_portal/f4.png"))); // NOI18N
        jLabel6.setText("f7057419");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 40, 690, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    BuscasTerceirizacao BT = new BuscasTerceirizacao(txtChave.getText(), txtSenha.getText());
        try {
        try {          
            BT.capturaInfos();
        } catch (SQLException ex) {
            Logger.getLogger(frmSubsifiosPendentesNoPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        } catch (IOException ex) {
            ex.printStackTrace();
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        
}//GEN-LAST:event_jButton1ActionPerformed

private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
// TODO add your handling code here:
    System.exit(0);
   
}//GEN-LAST:event_jLabel4MouseClicked

private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

}//GEN-LAST:event_jLabel3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BuscasSubsidiosPendentes BH = new BuscasSubsidiosPendentes(txtChave.getText(), txtSenha.getText());
        try {
            try {
                BH.capturaInfos();
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
        } catch (IOException ex) {
       
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChaveActionPerformed

    private void txtChaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChaveKeyReleased
        // TODO add your handling code here:
         int size = txtChave.getText().length();
        if (size == 8) {
            txtSenha.requestFocus();
        }
        if (size > 8) {
            txtChave.setText(txtChave.getText().substring(0, 8));
        }
    }//GEN-LAST:event_txtChaveKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSubsifiosPendentesNoPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSubsifiosPendentesNoPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSubsifiosPendentesNoPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSubsifiosPendentesNoPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmSubsifiosPendentesNoPortal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtChave;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
